### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hasit** [TPadTabletProject/TPadSoftware#1]
What license does this project have? What license do we, as developers who use this library, use for our code?

**Comment by TPadTabletProject** [comment]
Hey Hasit, sorry this slipped by. I'm not sure what you mean. The TPad
Tablet Project Software is Creative Commons
Attribution-NonCommercial-ShareAlike 3.0 Unported License
http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US.
Is this what you meant?

**Comment by hasit** [comment]
@TPadTabletProject 

That is what I meant. Thank you.
